<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>

		<AssemblyVersion>0.1.0.0</AssemblyVersion>
		<FileVersion>0.1.0.0</FileVersion>

		<PackageId>HDev.Hm.Logging.Core</PackageId>
		<Authors>Holmes Mojica</Authors>
		<Company>Holmes Mojica Dev</Company>

		<Description>
			Structured logging library for modern .NET applications featuring immutable log processing, distributed tracing integration, nested scope propagation, provider isolation, and resilient multi-provider orchestration.
		</Description>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<PropertyGroup>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>latest-recommended</AnalysisLevel>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
	</PropertyGroup>

	<PropertyGroup>
		<RepositoryUrl>https://github.com/holmesmojica-dev/hm-logging</RepositoryUrl>
		<PackageProjectUrl>https://github.com/holmesmojica-dev/hm-logging</PackageProjectUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>logging;structured-logging;observability;tracing;microservices;dotnet</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<PackageIcon>icon.png</PackageIcon>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<DebugType>portable</DebugType>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
	</PropertyGroup>

	<PropertyGroup Condition="'$(ReleaseVersion)' != ''">
		<Version>$(ReleaseVersion)</Version>
		<PackageVersion>$(ReleaseVersion)</PackageVersion>
		<FileVersion>$([System.Text.RegularExpressions.Regex]::Match('$(ReleaseVersion)', '^\d+\.\d+\.\d+').Value).0</FileVersion>
	</PropertyGroup>
	
	<ItemGroup>
	  <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.7" />
	  <PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.401">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
	  </PackageReference>
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\README.md"
			  Pack="true"
			  PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<None Include="..\..\icon.png"
			  Pack="true"
			  PackagePath="\" />
	</ItemGroup>

</Project>
