name: SonarCloud Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: Install SonarScanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: Add .NET tools to PATH
        run: echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Begin SonarCloud analysis
        run: >
          dotnet sonarscanner begin
          /k:"hm-logging"
          /o:"holmesmojica-dev"
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          /d:sonar.host.url="https://sonarcloud.io"

      - name: Restore
        run: dotnet restore Hm.Logging.sln

      - name: Build
        run: dotnet build Hm.Logging.sln --configuration Release --no-restore --no-incremental

      - name: End SonarCloud analysis
        run: >
          dotnet sonarscanner end
          /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
